version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0  # Bind to all interfaces inside the container
      FLASK_RUN_PORT: 5000     # Ensure Flask runs on port 5000
      DB_USERNAME: "admin"
      DB_ENDPOINT: "database-1.cgtoqkc9cnse.us-east-1.rds.amazonaws.com"
      DB_NAME: "rds_usersdb"
      JWT_SECRET_KEY: "myjwtpythonsecret"
      DB_PASSWORD_FILE: /run/secrets/db_password  # Reference to the secret file
    volumes:
      - ./db_password.txt:/run/secrets/db_password:ro