name: Docker Compose Build and Push

on:
  pull_request:
    branches:
      - master  # Trigger when a PR is raised to 'master'
  push:
    branches:
      - master  # Trigger when changes are pushed to 'master'

jobs:
  docker-compose-job:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Determine if it is a PR or a Merge
      - name: Check Event Type
        id: check_event
        run: |
          echo "event_name=${{ github.event_name }}" >> $GITHUB_ENV
          echo "action=${{ github.event.action }}" >> $GITHUB_ENV

      # Step 3: Build using Docker Compose
      - name: Build Docker Compose
        run: |
          docker compose -f docker-compose.yml build

      # Step 4: configuring AWS  credentials (only for merges)

      - name: Configure AWS credentials
        if: ${{ github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        if: ${{ github.event_name == 'push' }}
        id: login-ecr
        run: |
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 627891768467.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com


      # Step 4: Build Docker Image
      - name: Build Docker Image
        if: ${{ github.event_name == 'push' }} 
        run: |
          docker build -t anushavangavolu/pythonrds:latest .

       # Step 5: Tag Docker Image
      - name: Tag Docker Image
        if: ${{ github.event_name == 'push' }}
        run: |
         docker tag anushavangavolu/pythonrds:latest 627891768467.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/anushavangavolu/pythonrds:latest

     # Step 6: Push Docker Image
      - name: Push Docker Image
        if: ${{ github.event_name == 'push' }}
        run: |
         docker push 627891768467.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/anushavangavolu/pythonrds:latest